name: Privileged
description: You are part of the @fastapilabs team. If not, check the other options. 👇
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in this project! 🚀

        If you are not part of the @fastapilabs team, please start the conversation in a [Question in GitHub Discussions](https://github.com/fastapilabs/fastapi-cloud-cli/discussions/categories/questions) instead.
  - type: checkboxes
    id: privileged
    attributes:
      label: Privileged issue
      description: Confirm that you are allowed to create an issue here.
      options:
        - label: I'm part of the @fastapilabs team.
          required: true
  - type: textarea
    id: content
    attributes:
      label: Issue Content
      description: Add the content of the issue here.
